spring:
  profiles:
    active: dev

# 第三方登录
justAuth:
  clientId:
    gitee: 3b7e01dd6c8cb22d4834afbeb8058bd4b3db49f3994f6185c033e91a44638a81
    github: 62233222a97bac3e8c3e
    qq: XXXXXXXXXXXXXXX
  clientSecret:
    gitee: a6aa06c7bc8fa1bb3fec3e479267a3947378c4b57cc1d5dcfe9f0015a9862c7f
    github: e3910c863c4e93d07b4ad66919b08df45e2f0432
    qq: XXXXXXXXXXXXXXXXXX
  redirectUri:
    gitee: http://localhost:8080/oauth/callback/gitee
    github: http://localhost:8080/oauth/callback/github
    qq: xxxxxxxxxxxx
